<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta http-equiv="Content-Style-Type" content="text/css" />
  <meta name="generator" content="pandoc" />
  <title></title>
  <style type="text/css">code{white-space: pre;}</style>
  <style type="text/css">
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; }
code > span.dt { color: #902000; }
code > span.dv { color: #40a070; }
code > span.bn { color: #40a070; }
code > span.fl { color: #40a070; }
code > span.ch { color: #4070a0; }
code > span.st { color: #4070a0; }
code > span.co { color: #60a0b0; font-style: italic; }
code > span.ot { color: #007020; }
code > span.al { color: #ff0000; font-weight: bold; }
code > span.fu { color: #06287e; }
code > span.er { color: #ff0000; font-weight: bold; }
  </style>
  <link rel="stylesheet" href="github-markdown.css" type="text/css" />
</head>
<body>
<h1 id="data-and-analysis-for-unequal-representation-and-gender-stereotypes-in-image-search-results-for-occupations">Data and analysis for <em>Unequal representation and gender stereotypes in image search results for occupations</em></h1>
<p><a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img
alt="This work is licensed under a Creative Commons Attribution 4.0 International License" 
title="This work is licensed under a Creative Commons Attribution 4.0 International License" 
src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a> <em>Matthew Kay ([mjskay@uw.edu] (mailto:mjskay@uw.edu)), Cynthia Matuszek ([cmat@umbc.edu] (mailto:cmat@umbc.edu)), and Sean Munson ([smunson@uw.edu] (mailto:smunson@uw.edu))</em></p>
<p>This repository contains data and analysis code from:</p>
<p>Kay, Matthew, Matuszek, Cynthia, and Munson, Sean. Unequal Representation and Gender Stereotypes in Image Search Results for Occupations. <em>CHI 2015: Proceedings of the SIGCHI Conference on Human Factors in Computing Systems</em> (upcoming). http://dx.doi.org/10.1145/2702123.2702520</p>
<p>This file is structured as an extended version of the above paper, with inline R code for running the analyses. It is generated by README.Rmd (an [RMarkdown] (http://rmarkdown.rstudio.com/) file). The intent is to allow both for reproduction of our analyses, as well as replication and extension of our analyses. We would love to hear about any new analyses you conduct based on this work, or problems/improvements you have with the analyses contained herein. Please email us!</p>
<h2 id="citing-this-work">Citing this work</h2>
<p>Please cite the CHI paper above.</p>
<h2 id="libraries-needed-for-the-analyses-in-this-paper">Libraries needed for the analyses in this paper</h2>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(Matching)   <span class="co">#ks.boot</span>
<span class="kw">library</span>(visreg)     <span class="co">#visreg</span>
<span class="kw">library</span>(boot)       <span class="co">#logit, inv.logit (could use qlogis/plogis but this is clearer) </span>
<span class="kw">library</span>(pscl)       <span class="co">#vuong</span>
<span class="kw">library</span>(plyr)       <span class="co">#**ply</span>
<span class="kw">library</span>(ordinal)    <span class="co">#clmm</span>
<span class="kw">library</span>(lme4)       <span class="co">#lmer, glmer</span>
<span class="kw">library</span>(lmerTest)   <span class="co">#p-values with lmer</span>
<span class="kw">library</span>(car)        <span class="co">#Anova</span>
<span class="kw">library</span>(ggplot2)    <span class="co">#ggplot</span>
<span class="kw">library</span>(MuMIn)      <span class="co">#r.squaredGLMM</span>
<span class="kw">library</span>(pander)     <span class="co">#pander</span></code></pre>
<h1 id="unequal-representation-and-gender-stereotypes-in-image-search-results-for-occupations">Unequal representation and gender stereotypes in image search results for occupations</h1>
<h2 id="abstract">Abstract</h2>
<p>Information environments have the power to affect people’s perceptions and behaviors. In this paper, we present the results of studies in which we characterize the gender bias present in image search results for a variety of occupations. We experimentally evaluate the effects of bias in image search results on the images people choose to represent those careers and on people’s perceptions of the prevalence of men and women in each occupation. We find evidence for both stereotype exaggeration and systematic underrepresentation of women in search results. We also find that people rate search results higher when they are consistent with stereotypes for a career, and shifting the representation of gender in image search results can shift people’s perceptions about real-world distributions. We also discuss tensions between desires for high-quality results and broader societal goals for equality of representation in this space.</p>
<h2 id="introduction">Introduction</h2>
<p>Every day, billions of people interact with interfaces that help them access information and make decisions. As increasing amounts of information become available, systems designers turn to algorithms to select which information to show to whom. These algorithms and the interfaces built on them can influence people’s behaviors and perceptions about the world. Both algorithms and interfaces, however, can be biased in how they represent the world [10,35]. These biases can be particularly insidious when they are not transparent to the user or even to the designer [29]. The information people access affects their understanding of the world around them and the decisions they make: biased information can affect both how people treat others and how they evaluate their own choices or opportunities.</p>
<p>One of the most prevalent and persistent biases in the United States is a bias against women with respect to occupational choices, opportunities, and compensation [21,27]. Stereotypes of many careers as gender-segregated serve to reinforce gender sorting into different careers and unequal compensation for men and women in the same career. Cultivation theory, traditionally studied in the context of television, contends that both the prevalence and characteristics of media portrayals can develop, reinforce, or challenge viewers’ stereotypes [30].</p>
<p>Inequality in the representation of women and minorities, and the role of online information sources in portraying and perpetuating it, have not gone unnoticed in the technology community. This past spring, Getty Images and LeanIn.org announced an initiative to increase the diversity of working women portrayed in the stock images and to improve how they are depicted [28]. A recent study identified discrimination in online advertising delivery: when searching for names, search results for black-identifying first names were accompanied by more ads for public records searches than those for white-identifying first names, and those results were more likely to suggest searches for arrest records [35]. These findings raise questions about the possible impacts of this discrimination and how to design technology in consideration of issues such as structural racism.</p>
<p>Despite efforts to address some of these issues, there has been limited public effort to measure how online information sources represent men and women. Further, we do not know how people perceive these biases when they view information sources, or the extent to which it affects their choices or perceptions about the world. For example, are gender distributions in search results representative of those in the real world – and if not, how does that affect people’s perceptions of the world?</p>
<p>In this paper, we begin to address these gaps through four studies characterizing how genders are represented in image search results for occupations. We evaluate whether and how these biases affect people’s perceptions of search result quality, their beliefs about the occupations represented, and the choices they make. In a series of studies on existing image search results, manipulated search results, and people’s perceptions of these results, we investigate the following phenomena:</p>
<ul>
<li><p><em>Stereotype exaggeration</em>: While gender proportions in image search results are close to those in actual occupations, results for many occupations exhibit a slight exaggeration of gender ratios according to stereotype: e.g., male-dominated professions tend to have even more men in their results than would be expected if the proportions reflected real-world distributions. This effect is also seen when people rate the quality of search results or select the best image from a result: they prefer images with genders that match the stereotype of an occupation, even when controlling for qualitative differences in images.</p></li>
<li><p><em>Systematic over-/under- representation</em>: Search results also exhibit a slight under-representation of women in images, such that an occupation with 50% women would be expected to have about 45% women in the results on average. However, when evaluating image result quality, people do not systematically prefer either gender: instead, stereotyping dominates, and they prefer images that match a given occupation’s gender stereotype.</p></li>
<li><p><em>Qualitative differential representation</em>: Image search results also exhibit biases in how genders are depicted: those matching the gender stereotype of a profession tend to be portrayed as more professional-looking and less inappropriate-looking.</p></li>
<li><p><em>Perceptions of occupations in search results</em>: We find that people’s existing perceptions of gender proportions in occupations are quite accurate (R<sup>2</sup> of 0.72), but that manipulated search results can have a small but significant effect on perceptions, shifting estimations on average ~7%.</p></li>
</ul>
<p>This last point contributes to the broader motivation of this work: not only to contribute to an understanding of how everyday information systems – here, image search results – both reflect and influence perceptions about gender in occupations, but also to characterize a possible design space for correcting or adjusting for differences in representation. We do not take a stance on whether or how designers and system builders should address gender inequality and its effects in their systems, but we believe that designers should be aware of inequalities in their systems and how those inequalities can affect perceptions. We particularly note two overriding design tensions in this space: the desire to improve perceived search result quality, and societal motivations for improving equality of representation.</p>
<p>In the remainder of this paper, we review motivating work and our specific research questions. We then describe four studies and their answers to these research questions before discussing the implications for designers and society.</p>
<h2 id="background-and-motivation">Background and motivation</h2>
<p>The Internet and large data sets create many new opportunities for engaging with data and using it in communication and to support decision making. They also come with challenges and pitfalls. A recent White House report noted that biases in data collection and presentation can lead to flawed understandings of the need for and use of public services, and that this can lead to discrimination in who receives those services [9].</p>
<p>In the studies presented in this paper, we investigate the prevalence and risks of gender-based stereotyping and bias in image search results for occupations. Our research questions were guided by prior work in stereotyping and biases, the role of media in forming, perpetuating, or challenging these, and contemporary discussions of the effects of stereotypes and biases information environments.</p>
<h3 id="stereotypes-and-bias">Stereotypes and bias</h3>
<p>A stereotype refers to a belief that individuals in a group – e.g., gender, occupation, race, ethnicity, or particular background – generally have one or more traits or behaviors. People make use of stereotypes to explain their own or others’ behaviors [15,36], to justify actions or decide how to act [4,36], and to define group boundaries [36]. While accurate stereotypes may be useful for making decisions in the absence of more specific information, inaccurate stereotypes can be harmful. Belief that one’s group performs poorly at a task can lead to lower performance (stereotype threat [33]). Stereotyped expectations about someone’s behavior can also lead them to behave in that way, a self-fulfilling prophecy [33,39], and expectations about one’s own abilities can influence aspirations and choices, such as beliefs about what career path one should follow [7,8].</p>
<p>Bias arises when an individual, group or process unfairly and systematically treats an individual or group favorably or unfavorably. Stereotypes about abilities or character are a common source of bias [18], often to the disadvantage of a particular race, sexual orientation, or gender. For example, stereotypes about gender and parental roles can systematically limit women’s career advancement [14,16,17].</p>
<h3 id="effects-of-stereotypes-and-bias-in-the-media">Effects of stereotypes and bias in the media</h3>
<p>The portrayal of women and racial/ethnic minorities in television and other media has received considerable attention as both a possible source of stereotypes and opportunity to challenge them [12]. Exclusion of these groups can imply that they are “unimportant, inconsequential, and powerless” [12]. Their inclusion offers specific examples whose implications depend on how they are portrayed, and these portrayals can reinforce or challenge stereotypes. Unfortunately, portrayals often reinforce negative stereotypes, for example by showing racial/ethnic minorities as criminals, victims of criminals, and in low-status service jobs [12].</p>
<p>Cultivation theory predicts that television’s portrayal of the world affects people’s beliefs about reality [11,32]. Portrayals, or the lack of portrayals, can affect whether people believe that people like them commonly participate in an occupation, or their perceived self-efficacy for that role [12,32]. Researchers studying television commercials find that women are less likely to be portrayed as workers and that they exaggerate gender-occupation stereotypes [6]. They express concern that such portrayals may perpetuate stereotypes. Cultivation theory has also been found to predict how people perceive risks after experiencing them in a video game [38], and playing a sexualized female character reduces female players’ feelings of self-efficacy [3].</p>
<h3 id="stereotypes-and-bias-in-information-systems">Stereotypes and bias in information systems</h3>
<p>Like media and other built systems or environments, computer systems have bias. Friedman and Nissenbaum describe biased computer systems as those that “systematically and unfairly discriminate against certain individuals or groups of individuals in favor of others” [10]. They describe three categories: preexisting bias (arising from biases present in individuals or society), technical bias (arising from technical constraints), and emergent bias (arising in real use, in which a system is mismatched for the capabilities or values of its users). They argue: “freedom from bias should be counted among the select set of criteria according to which the quality of systems in use in society should be judged.”</p>
<p>Search engines have been studied and received popular attention for bias in their results, both for what they index and present overall [20,37] and what they present to particular users [29]. People tend to rely on search engines’ selection and ordering of results as signs of quality and relevance [22,23], and so biased search results may affect people’s choices and beliefs. Scholars have previously noted bias in which geographic locations are indexed and listed [37]. Others express concern that search autocomplete features could perpetuate preexisting biases, noting that suggestions varied between different religious groups, and sexual and racial minorities received more negatively framed questions as suggestions [2]. As illustrated by these examples, a search engine which has neither algorithms that systematically favor one group nor designers with a particular bias can still perpetuate preexisting societal biases: a representative indexing of biased source material will produce results that contain the same biases.</p>
<p>More recently, Getty Images and Sheryl Sandberg’s Lean In Foundation announced an effort to improve the depiction of working women in stock photos. They argue that existing images support stereotypes of working women as sidelined, sexualized, or in supporting roles, and that these depictions hurt women’s career aspirations and prospects [13,25,28].</p>
<h2 id="research-questions">Research questions</h2>
<p>Motivated by these concerns and questions about them, we conducted a series of studies to evaluate bias in image search results. Pre-existing biases that affect the images available for image search systems, and algorithms designed to represent available content, may lead to biased result sets, which in turn affect people’s perceptions and choices among the search results. We specifically focus on gender representation in image search results for occupations. We choose the portrayal of occupations because it is a topic of societal importance that has recently received attention and efforts to ameliorate biases. While efforts such as the partnership between Getty Images and Lean In may make more diverse or positive images available, and particularly to those who access the Lean In collection, many people turn to major search engines when looking to illustrate a topic, and so we focus our attention on the image search results for a major search engine.</p>
<p>To the discussion of the bias in computer systems, we contribute an assessment of the current extent and form of several forms of stereotyping and differences of representation present in image search results: <em>stereotype exaggeration</em>, <em>systematic over-/under-representation</em>, and <em>qualitative differential representation</em>. We also explore the effects of these biases on perceptions of the occupations in question. We designed four studies to answer these research questions:</p>
<ul>
<li><p>Study 1: How does the prevalence of men and women in image search results for professions correspond to their prevalence in actual professions? Are genders systematically over or underrepresented across careers, and is there stereotype exaggeration in gender proportions?</p></li>
<li><p>Study 2: Are there qualitative differences in how men and women are portrayed in the image search results?</p></li>
<li><p>Study 3: Do biased image search results lead people to perpetuate a bias in image search results when they choose images to represent a profession (i.e. through stereotype exaggeration)? Are there systemic over- or under-representations of women in preferred results? How do differences in representation affect people’s perceptions of the search result quality?</p></li>
<li><p>Study 4: Do differences in representation in image search results affect viewers’ perceptions of the prevalence of men and women in that occupation? Can we shift those opinions by manipulating results?</p></li>
</ul>
<p>For all studies, we recruited turkers/participants<sup><a
name="footnote1_source" href="#footnote1">1</a></sup> from Amazon’s Mechanical Turk microtask market. We required that they be from the United States (as our occupation prevalence data is specific to that population) and, for studies 2-4, required them to have the Masters qualification.</p>
<h2 id="study-1-gender-proportions-in-results-compared-to-actual-proportions">Study 1: Gender proportions in results compared to actual proportions</h2>
<p>In this study, we sought to characterize the extent to which the prevalence of men and women in image search results for professions correspond to their actual prevalence in those occupations. As a gold standard for actual prevalence of men and women by occupation, we used estimates from the US Bureau of Labor and Statistics (BLS) [5]. We did not use all occupations, but removed occupations that:</p>
<ul>
<li><p>Presented difficult polysemy problems: for example, occupations that are listed as conjunctions of multiple occupations in the BLS, such as “Musicians, singers, and related workers”, are difficult to reduce to a single search.</p></li>
<li><p>Had non-obvious search terms: for example, “Miscellaneous media and communication workers”.</p></li>
<li><p>Are typically referred to using gender-specific terms: for example, “tailor” and “seamstress”</p></li>
</ul>
<p>Most of the remaining terms had straightforward translations from BLS categories into search terms for a worker in that occupation (for example, we mapped “Nurse practitioners” in the BLS database to the search term “nurse practitioner”). Some categories required limited interpretation (e.g., we translated “Police and sheriff’s patrol officers” into “police officer”); for these terms, all three authors had to agree on a corresponding search term for the category to be included. This left us with 96 occupations having an entry in BLS and a corresponding search term. The full BLS dataset is available in <code>data/public/bls_occupations.csv</code> and the set of 96 occupations chosen for labelling is in <code>data/public/labelled_bls_occupations.csv</code>.</p>
<p>We then downloaded the top 100 Google Image search results for each search term (from July 26–29, 2013). For each image, turkers were asked to indicate whether there were no people, one person, or more than one person in the image. They were also asked whether the people were women, men, children, or of unknown gender (and to check all that apply).<sup><a name="footnote2_source"
href="#footnote2">2</a></sup> We had three turkers label each image. The mturk template for that task is available at <code>mturk/label_gender_task.html</code>.</p>
<h3 id="results">Results</h3>
<h4 id="representativeness-of-filtered-dataset">Representativeness of filtered dataset</h4>
<p>A requirement of this study was to obtain a representative dataset of images of individuals in different occupations with properly labelled gender. This required some filtering to ensure that images had correctly labelled genders, depicted only people of that gender, and were generally images of people in the first place. To label gender, we took the majority label for each image, and dropped those images from the results which did not have majority agreement. We then dropped entire search terms which:</p>
<ul>
<li><p>Had less than 80% of the images labelled with majority agreement (two terms failed this criterion: firefighter and baker; notably, firefighter had only 64% agreement, largely because most of the images were dark silhouettes of uniformed firefighters with ambiguous gender, frequently labeled as “male” by some turkers).</p></li>
<li><p>Had few images containing only one gender or that mostly depicted workers with clients/patients. For example, hairdresser was dropped since too many of its images contained both hairdresser and client, making it difficult to determine which gender label corresponds to which. We considered asking turkers whether the person in question has the given occupation; however, this implicitly asks them to decide if a person of that gender could be a hairdresser (thus potentially subject to gender stereotypes related to that profession, which would bias our labelled data set), so we opted to filter occupations with multiple genders in the majority of images.</p></li>
<li><p>Had too few people in the image results; e.g., dishwasher largely returned images of dishwashing machines.</p></li>
<li><p>Corresponded with a common name (e.g., baker returned many results of people with the surname Baker).</p></li>
</ul>
<p>This second filtering process left us with 45 occupations. This dataset is is <code>data/public/filtered_bls_occupations.csv</code>. To ensure that all levels of our filtering (from the initial selection of search terms down to the filtering of labelled images) had not biased the representativeness of our final selection of occupations in terms of gender or ethnicity, we conducted a series of Kolmogorov-Smirnov tests comparing the gender and ethnicity distributions of the filtered 45 occupations to the entire set of 535 occupations in the BLS (using bootstrap p values; unlike the traditional KS test this allows for non-continuous distributions and ties):</p>
<pre class="sourceCode r"><code class="sourceCode r">occupations =<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;data/public/bls_occupations.csv&quot;</span>)
filtered_occupations =<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;data/public/filtered_bls_occupations.csv&quot;</span>)

for (colname in <span class="kw">c</span>(<span class="st">&quot;p_women&quot;</span>, <span class="st">&quot;p_asian&quot;</span>, <span class="st">&quot;p_black&quot;</span>, <span class="st">&quot;p_hispanic&quot;</span>)) {
    <span class="co">#plot CDF comparison for this group</span>
    <span class="kw">plot</span>(<span class="kw">ecdf</span>(occupations[[colname]]), <span class="dt">col=</span><span class="st">&quot;red&quot;</span>, <span class="dt">pch=</span><span class="ot">NA</span>, 
        <span class="dt">main=</span><span class="kw">paste</span>(<span class="st">&quot;Comparison of ECDFs</span><span class="ch">\n</span><span class="st">of&quot;</span>, colname))
    <span class="kw">lines</span>(<span class="kw">ecdf</span>(filtered_occupations[[colname]]), <span class="dt">verticals=</span><span class="ot">TRUE</span>, 
        <span class="dt">pch=</span><span class="ot">NA</span>, <span class="dt">col=</span><span class="st">&quot;black&quot;</span>)
    <span class="kw">legend</span>(<span class="st">&quot;bottomright&quot;</span>, <span class="kw">c</span>(<span class="st">&quot;Full&quot;</span>, <span class="st">&quot;Filtered&quot;</span>), <span class="dt">col=</span><span class="kw">c</span>(<span class="st">&quot;red&quot;</span>, <span class="st">&quot;black&quot;</span>), 
        <span class="dt">lty=</span><span class="st">&quot;solid&quot;</span>, <span class="dt">lwd=</span><span class="dv">1</span>, <span class="dt">text.col=</span><span class="st">&quot;black&quot;</span>, <span class="dt">bty=</span><span class="st">&quot;n&quot;</span>)
    
    <span class="co">#run KS test (default formatting leaves something to be desired,</span>
    <span class="co">#so we&#39;ll give more detail ourselves here)</span>
    ks.result =<span class="st"> </span><span class="kw">ks.boot</span>(filtered_occupations[[colname]], occupations[[colname]])    
    <span class="kw">cat</span>(<span class="st">&quot;Two-sample Kolmogorov-Smirnov test</span><span class="ch">\n</span><span class="st">&quot;</span>,
        <span class="st">&quot;Null hyp: distribution of &quot;</span>, colname, <span class="st">&quot; for occupations in full dataset</span><span class="ch">\n</span><span class="st">&quot;</span>,
        <span class="st">&quot;          is the same as the distribution of &quot;</span>, colname, 
        <span class="st">&quot; for occupations in filtered dataset</span><span class="ch">\n</span><span class="st">&quot;</span>,
        <span class="st">&quot;D_&quot;</span>, <span class="kw">nrow</span>(filtered_occupations), <span class="st">&quot;,&quot;</span>, <span class="kw">nrow</span>(occupations), <span class="st">&quot; = &quot;</span>, 
        ks.result$ks$statistic[<span class="dv">1</span>], <span class="st">&quot;</span><span class="ch">\n</span><span class="st">&quot;</span>, <span class="dt">sep=</span><span class="st">&quot;&quot;</span>)
    <span class="kw">print</span>(<span class="kw">summary</span>(ks.result))
}</code></pre>
<div class="figure">
<img src="figure/ks_tests-1.png" alt="plot of chunk ks_tests" /><p class="caption">plot of chunk ks_tests</p>
</div>
<pre><code>## Two-sample Kolmogorov-Smirnov test
## Null hyp: distribution of p_women for occupations in full dataset
##           is the same as the distribution of p_women for occupations in filtered dataset
## D_45,535 = 0.0996997
## 
## Bootstrap p-value:     0.763 
## Naive p-value:         0.82557 
## Full Sample Statistic: 0.0997</code></pre>
<div class="figure">
<img src="figure/ks_tests-2.png" alt="plot of chunk ks_tests" /><p class="caption">plot of chunk ks_tests</p>
</div>
<pre><code>## Two-sample Kolmogorov-Smirnov test
## Null hyp: distribution of p_asian for occupations in full dataset
##           is the same as the distribution of p_asian for occupations in filtered dataset
## D_45,535 = 0.09009009
## 
## Bootstrap p-value:     0.793 
## Naive p-value:         0.90448 
## Full Sample Statistic: 0.09009</code></pre>
<div class="figure">
<img src="figure/ks_tests-3.png" alt="plot of chunk ks_tests" /><p class="caption">plot of chunk ks_tests</p>
</div>
<pre><code>## Two-sample Kolmogorov-Smirnov test
## Null hyp: distribution of p_black for occupations in full dataset
##           is the same as the distribution of p_black for occupations in filtered dataset
## D_45,535 = 0.1021021
## 
## Bootstrap p-value:     0.729 
## Naive p-value:         0.80298 
## Full Sample Statistic: 0.1021</code></pre>
<div class="figure">
<img src="figure/ks_tests-4.png" alt="plot of chunk ks_tests" /><p class="caption">plot of chunk ks_tests</p>
</div>
<pre><code>## Two-sample Kolmogorov-Smirnov test
## Null hyp: distribution of p_hispanic for occupations in full dataset
##           is the same as the distribution of p_hispanic for occupations in filtered dataset
## D_45,535 = 0.1423423
## 
## Bootstrap p-value:     0.334 
## Naive p-value:         0.39797 
## Full Sample Statistic: 0.14234</code></pre>
<p>We did not find evidence that our filtered dataset significantly differed from the set of occupations in the BLS in terms of gender distribution, distribution of Asian people, distribution of Black or African American people, or distribution of Hispanic or Latino people. Note the close correspondence of empirical cumulative distribution functions for the filtered dataset versus the full BLS dataset.</p>
<h4 id="misrepresentation-of-genders-in-search-results">Misrepresentation of genders in search results</h4>
<p>We ran several models to assess the possibility of systematic differences of representation in depictions of occupations in image search results compared to the known proportions in the BLS. The purpose of these models was to assess the presence of two potential forms of quantitative differences in representation.</p>
<p>The first is that gender proportions are exaggerated according to stereotypes for each career (stereotype exaggeration). For example, if stereotyping occurs in image results, we would expect a profession with 75% males in the BLS to have more than 75% males in the image results. The second possibility is that there is a systematic overrepresentation of one gender, across all careers, in the search results.</p>
<h4 id="stereotype-exaggeration-by-career">Stereotype exaggeration by career</h4>
<p>To assess whether men or women were over- or under-represented according to stereotypes for careers, we ran two logistic regression models: a stereotyped and a non-stereotyped model. The stereotyped model regressed the logit of the proportion of women in the search results on the proportion of women in BLS:</p>
<pre class="sourceCode r"><code class="sourceCode r">proportions =<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;data/public/filtered_bls_occupations_with_search_gender_proportions.csv&quot;</span>)

<span class="co">#we set the x-intercept to -0.5 so that the model intercept</span>
<span class="co">#represents deviation from equal representation (note that</span>
<span class="co">#logit(0.5) = 0, so if there is no systematic over/under</span>
<span class="co">#representation we would expect the intercept of this model to</span>
<span class="co">#be ~0). This is mainly a convenience for the analysis below</span>
<span class="co">#as even if we did not do this an equivalent model would result</span>
<span class="co">#(just with slightly harder to interpret coefficients).</span>
m.stereotyped =<span class="st"> </span><span class="kw">glm</span>(search_p_women ~<span class="st"> </span><span class="kw">I</span>(bls_p_women -<span class="st"> </span><span class="fl">0.5</span>), 
    <span class="dt">family=</span>quasibinomial, <span class="dt">data=</span>proportions, <span class="dt">weights=</span>search_n)</code></pre>
<p>This model exhibits an s-curve characteristic of the logit of a proportion and indicative of stereotyping: extreme gender proportions in the BLS are pulled even more to the extremes in the search results:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co">#plot fit and points</span>
<span class="kw">visreg</span>(m.stereotyped, <span class="dt">scale=</span><span class="st">&quot;response&quot;</span>, <span class="dt">rug=</span><span class="ot">FALSE</span>)
<span class="kw">points</span>(search_p_women ~<span class="st"> </span>bls_p_women, <span class="dt">data=</span>proportions, <span class="dt">pch=</span><span class="dv">20</span>)
<span class="co">#add some reference lines</span>
<span class="kw">abline</span>(<span class="dt">coef=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), <span class="dt">lty=</span><span class="st">&quot;dashed&quot;</span>)
<span class="kw">abline</span>(<span class="dt">v=</span>.<span class="dv">5</span>, <span class="dt">lty=</span><span class="st">&quot;dashed&quot;</span>)</code></pre>
<div class="figure">
<img src="figure/stereotyped_model_plot-1.png" alt="plot of chunk stereotyped_model_plot" /><p class="caption">plot of chunk stereotyped_model_plot</p>
</div>
<p>The non-stereotyped model regressed the logit of the proportion of women in the search results on the logit of the proportion of women in BLS, thus not exhibiting an s-curve:</p>
<pre class="sourceCode r"><code class="sourceCode r">m.nonstereotyped =<span class="st"> </span><span class="kw">glm</span>(search_p_women ~<span class="st"> </span><span class="kw">logit</span>(bls_p_women),
    <span class="dt">family=</span>quasibinomial, <span class="dt">data=</span>proportions, <span class="dt">weights=</span>search_n)

<span class="co">#plot fit and points</span>
<span class="kw">visreg</span>(m.nonstereotyped, <span class="dt">scale=</span><span class="st">&quot;response&quot;</span>, <span class="dt">rug=</span><span class="ot">FALSE</span>)
<span class="kw">points</span>(search_p_women ~<span class="st"> </span>bls_p_women, <span class="dt">data=</span>proportions, <span class="dt">pch=</span><span class="dv">20</span>)
<span class="co">#add some reference lines</span>
<span class="kw">abline</span>(<span class="dt">coef=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), <span class="dt">lty=</span><span class="st">&quot;dashed&quot;</span>)
<span class="kw">abline</span>(<span class="dt">v=</span>.<span class="dv">5</span>, <span class="dt">lty=</span><span class="st">&quot;dashed&quot;</span>)</code></pre>
<div class="figure">
<img src="figure/nonstereotyped_model-1.png" alt="plot of chunk nonstereotyped_model" /><p class="caption">plot of chunk nonstereotyped_model</p>
</div>
<p>While both models can account for a systematic over-representation of one gender across careers, only the stereotyped model can account for the pulling at the extremes characteristic of stereotyping by the typical gender of a career.</p>
<p>We found some evidence for stereotype exaggeration: the stereotyped model had qualitatively better residual fit, which we can see by comparing plots of the residual fits:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(m.stereotyped, <span class="dt">which=</span><span class="dv">1</span>)</code></pre>
<div class="figure">
<img src="figure/nonstereotyped_model_plot-1.png" alt="plot of chunk nonstereotyped_model_plot" /><p class="caption">plot of chunk nonstereotyped_model_plot</p>
</div>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(m.nonstereotyped, <span class="dt">which=</span><span class="dv">1</span>)</code></pre>
<div class="figure">
<img src="figure/nonstereotyped_model_plot-2.png" alt="plot of chunk nonstereotyped_model_plot" /><p class="caption">plot of chunk nonstereotyped_model_plot</p>
</div>
<p>We can also compare the models using Vuong’s closeness test for model fit:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co">#N.B. we refit binomial models instead of quasibinomial because</span>
<span class="co">#Vuong&#39;s test requires MLE-based models. We also use the</span>
<span class="co">#direct (case-by-case) data rather than a data table of </span>
<span class="co">#proportions and counts because the vuong function requires it.</span>
images =<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;data/public/gender_labelled_images.csv&quot;</span>)
m.stereotyped<span class="fl">.2</span> =<span class="st"> </span><span class="kw">glm</span>(image_gender ~<span class="st"> </span><span class="kw">I</span>(bls_p_women -<span class="st"> </span><span class="fl">0.5</span>), <span class="dt">family=</span>binomial, <span class="dt">data=</span>images)
m.nonstereotyped<span class="fl">.2</span> =<span class="st"> </span><span class="kw">glm</span>(image_gender ~<span class="st"> </span><span class="kw">logit</span>(bls_p_women), <span class="dt">family=</span>binomial, <span class="dt">data=</span>images)

<span class="co">#stop if the coefficients of these models aren&#39;t the same as the models fit above</span>
<span class="kw">stopifnot</span>(<span class="kw">all.equal</span>(<span class="kw">coef</span>(m.stereotyped), <span class="kw">coef</span>(m.stereotyped<span class="fl">.2</span>))) 
<span class="kw">stopifnot</span>(<span class="kw">all.equal</span>(<span class="kw">coef</span>(m.nonstereotyped), <span class="kw">coef</span>(m.nonstereotyped<span class="fl">.2</span>))) 

<span class="kw">vuong</span>(m.stereotyped<span class="fl">.2</span>, m.nonstereotyped<span class="fl">.2</span>)</code></pre>
<pre><code>## Vuong Non-Nested Hypothesis Test-Statistic: 1.545984 
## (test-statistic is asymptotically distributed N(0,1) under the
##  null that the models are indistinguishible)
## in this case:
## model1 &gt; model2, with p-value 0.061054</code></pre>
<p>The Vuong test also suggested that the stereotyped model had better fit. This stereotyping effect can be seen as the overall s-shape of the data compared to a line with slope = 1 (we would expect a line with slope = 1 if the data did not exhibit stereotype exaggeration).</p>
<h4 id="systematic-over-under--representation-across-careers">Systematic over-/under- representation across careers</h4>
<p>We can estimate overrepresentation of a gender across careers from our logistic regression model by testing to see if the coefficient of the intercept is significantly different from 0 when the x-intercept is set to 50% women in the BLS. Since we fit the model with that x-intercept already, it suffices to examine the intercept of the fitted model:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co">#regression model coefficients and confidence intervals</span>
<span class="kw">summary</span>(m.stereotyped)</code></pre>
<table>
<caption>Fixed effects</caption>
<thead>
<tr class="header">
<th align="center"> </th>
<th align="center">Estimate</th>
<th align="center">Std. Error</th>
<th align="center">t value</th>
<th align="center">p</th>
<th align="center"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">(Intercept)</td>
<td align="center">-0.2604</td>
<td align="center">0.0971</td>
<td align="center">-2.682</td>
<td align="center">0.01034</td>
<td align="center">*</td>
</tr>
<tr class="even">
<td align="center">I(bls_p_women - 0.5)</td>
<td align="center">5.331</td>
<td align="center">0.3773</td>
<td align="center">14.13</td>
<td align="center">9.23e-18</td>
<td align="center">***</td>
</tr>
</tbody>
</table>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">confint</span>(m.stereotyped)</code></pre>
<pre><code>##                           2.5 %      97.5 %
## (Intercept)          -0.4511975 -0.07004516
## I(bls_p_women - 0.5)  4.6151838  6.09629887</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co">#coefficients as odds ratios</span>
<span class="kw">exp</span>(<span class="kw">coef</span>(m.stereotyped))</code></pre>
<pre><code>##          (Intercept) I(bls_p_women - 0.5) 
##            0.7707274          206.5835542</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">exp</span>(<span class="kw">confint</span>(m.stereotyped))</code></pre>
<pre><code>##                           2.5 %      97.5 %
## (Intercept)            0.636865   0.9323517
## I(bls_p_women - 0.5) 101.006392 444.2106410</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co">#coefficients as percentages at 50% women</span>
<span class="kw">inv.logit</span>(<span class="kw">coef</span>(m.stereotyped))</code></pre>
<pre><code>##          (Intercept) I(bls_p_women - 0.5) 
##            0.4352603            0.9951827</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">inv.logit</span>(<span class="kw">confint</span>(m.stereotyped))</code></pre>
<pre><code>##                          2.5 %    97.5 %
## (Intercept)          0.3890761 0.4824959
## I(bls_p_women - 0.5) 0.9901967 0.9977539</code></pre>
<p>Indeed, we find that the intercept does have a significant effect in this model (estimated effect: −0.26, 95% confidence interval: [−0.45, −0.07], t43 = −2.68, p &lt; 0.05);<sup><a name="footnote3_source" href="#footnote3">3</a></sup> this effect can be seen in Figure 2 as a dip in the predicted proportion of women in the search results at (50%, 50%). This effect corresponds to an odds ratio of approximately 0.77 (95% CI: [0.64, 0.93]); this means that in a profession with 50% women, we would expect about 45% of the images to be women on average (95% CI: [38.9%, 48.2%]).</p>
<p>The particular combination of stereotype exaggeration and underrepresentation of women that we see – slight pulling at the extremes and slight bias towards male images – combine to affect male- and female-dominated professions differently. In male-dominated professions (lower-left quadrant of stereotyped model plot) both effects amplify each other, so a higher proportion of males appear in search results than are in the BLS. By contrast, in female-dominated professions (upper-right quadrant) these two effects essentially cancel each other out, leading to a similar proportion of women in the search results as are in the BLS.</p>
<h2 id="study-2-differences-in-qualitative-representation">Study 2: Differences in qualitative representation</h2>
<p>Search results can be biased even when their gender proportions are representative. For example, in reviewing the images collected for Study 1, we identified many examples of sexualized depictions of women who were almost certainly not engaged in the profession they portrayed; we dub this the <strong>sexy construction worker problem</strong>, as images of female construction workers in our results tended to be sexualized caricatures of construction workers. We wished to assess whether images that better match the stereotypical gender of a profession were systematically portrayed as more or less professional, attractive, or appropriate. Note that while there are many interesting differences to unpack here, our primary focus is on assessing these characteristics so that we can control for them in subsequent analysis.</p>
<h3 id="methods">Methods</h3>
<p>We used the top 8 male and female images from each profession, as these images will be used again in study 3, below. Initially, we piloted a study in which people were asked to give 5 adjectives describing the person in each image, but found that this task was too difficult. We therefore opted to select 8 adjectives derived from our pilot results and our research questions: attractive, provocative, sexy, professional, competent, inappropriate, trustworthy, and weird. We then had turkers indicate on a 5-point scale (strongly disagree to strongly agree) whether they felt each adjective described the person in the picture. Each turker could rate each image at most once, though no turker could rate more than 600 images. Each image was rated by at least 3 turkers.</p>
<h3 id="results-1">Results</h3>
<p>At a high level, we found that images showing a person matching the majority gender for a profession tend to be ranked as slightly more professional-looking and slightly less inappropriate than those going against stereotype.</p>
<h3 id="adjective-ratings">Adjective ratings</h3>
<p>One would expect that men and women rate images differently; however, this is not our focus here, so we have attempted to factor out these differences. We conducted a series of mixed-effects ordinal logistic regressions to model how turkers rated images for each adjective. We included the turker’s gender, the image gender, and their interaction as fixed effects; we included the turker and the image as random effects.<sup><a name="footnote4_source"
href="#footnote4">4</a></sup> This allows our models to account for (for example) situations where women systematically rate men as more attractive than men do.</p>
<pre class="sourceCode r"><code class="sourceCode r">adjective_ratings =<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;data/public/image_adjective_ratings.csv&quot;</span>)

<span class="co">#make adjectives ordered factors</span>
adjectives =<span class="st"> </span><span class="kw">colnames</span>(adjective_ratings)[<span class="dv">9</span>:<span class="dv">16</span>]
adjective_ratings[,adjectives] =<span class="st"> </span><span class="kw">llply</span>(adjective_ratings[,adjectives], function (adjective) 
    <span class="kw">ordered</span>(adjective, <span class="dt">levels=</span><span class="kw">c</span>(<span class="st">&quot;strongly disagree&quot;</span>, <span class="st">&quot;disagree&quot;</span>, <span class="st">&quot;neutral&quot;</span>, <span class="st">&quot;agree&quot;</span>, <span class="st">&quot;strongly agree&quot;</span>)))

<span class="co">#build a list mapping each adjective name onto its ordinal model</span>
m.adjectives =<span class="st"> </span><span class="kw">llply</span>(adjectives, function(adjective)
    <span class="kw">clmm</span>(adjective_ratings[[adjective]] ~<span class="st"> </span>turker_gender *<span class="st"> </span>image_gender +<span class="st"> </span>(<span class="dv">1</span>|turker) +<span class="st"> </span>(<span class="dv">1</span>|image_url), 
        <span class="dt">data=</span>adjective_ratings))
<span class="kw">names</span>(m.adjectives) =<span class="st"> </span>adjectives</code></pre>
<p>We used the coefficients of the image effect in each model as a normalized rating for that adjective on that image:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co">#make data frame with only one row per rated image to hold normalized ratings</span>
<span class="co">#columns 3:8 are image and occupation characteristics</span>
rated_images =<span class="st"> </span><span class="kw">ddply</span>(adjective_ratings, ~<span class="st"> </span>image_url, function(df) df[<span class="dv">1</span>,<span class="dv">3</span>:<span class="dv">8</span>])

<span class="co">#add the normalized adjective ratings to the rated images</span>
for (adjective in adjectives) {
    standardized_adjective =<span class="st"> </span><span class="kw">ranef</span>(m.adjectives[[adjective]])$image_url
    rated_images[[adjective]] =<span class="st"> </span>standardized_adjective[rated_images$image_url,]
}</code></pre>
<p>These ratings have the effects of turker, turker gender, image gender, and their interaction factored out and are all approximately standard normally distributed.</p>
<h3 id="stereotyping-bias-in-qualitative-ratings">Stereotyping bias in qualitative ratings</h3>
<p>We hypothesized that images matching the typical gender of a given profession might be portrayed differently from images that do not match the typical gender of that profession (as in the sexy construction worker problem). To assess the whether this was the case, we ran linear mixed-effects regressions, each with one of the adjective ratings derived above as the independent variable. Each model included image gender, the image gender proportion in BLS (the % of people in the BLS matching the gender of the image; e.g. for a male image of a construction worker, this would be the % of construction workers who are male according to the BLS), and the interaction of these two terms as fixed effects. The models also included the occupation as a random effect. As noted above, we are primarily interested in these factors as controls in Study 3 (below), so we only summarize two high-level trends in the results here.</p>
<pre><code>Anova(lmer(professional ~ image_gender*bls_p_image_gender + (1|search_term), 
    data=rated_images), test=&quot;F&quot;)
Anova(lmer(attractive ~ image_gender*bls_p_image_gender + (1|search_term), 
    data=rated_images), test=&quot;F&quot;)
Anova(lmer(sexy ~ image_gender*bls_p_image_gender + (1|search_term), 
    data=rated_images), test=&quot;F&quot;)
Anova(lmer(competent ~ image_gender*bls_p_image_gender + (1|search_term), 
    data=rated_images), test=&quot;F&quot;)
Anova(lmer(inappropriate ~ image_gender*bls_p_image_gender + (1|search_term), 
    data=rated_images), test=&quot;F&quot;)
Anova(lmer(trustworthy ~ image_gender*bls_p_image_gender + (1|search_term), 
    data=rated_images), test=&quot;F&quot;)
Anova(lmer(provocative ~ image_gender*bls_p_image_gender + (1|search_term), 
    data=rated_images), test=&quot;F&quot;)
</code></pre>
<p>First, adjectives like professional (F1,623.6 = 36.6, p &lt; 0.0001), competent (F1,630 = 28.4, p &lt; 0.0001), and trustworthy (F1,627.8 = 33.8, p &lt; 0.0001) had significantly higher ratings when the proportion of people in the BLS matching the gender of the image was higher. Second, adjectives like inappropriate (F1,635.2 = 20.4, p &lt; 0.0001) or provocative (F1,635.12 = 4.38, p &lt; 0.05) had significantly lower ratings when the proportion of people in the BLS matching the gender of the image was higher. In other words, we again we see an effect of stereotyping exaggeration: images matching the gender stereotype of a profession tend to be slightly more professional-looking and slightly less inappropriate than those going against stereotype. The reason for this effect is unclear: it may be that these images are rated less professional/appropriate because of raters’ biases against images going against their stereotypes for those professions. However, it may also be that these depictions are of lower quality – examples of the sexy construction worker problem, where depictions against stereotype are not true depictions of the profession at all.</p>
<h2 id="study-3-perceptions-of-search-results">Study 3: Perceptions of search results</h2>
<p>Having described the bias present in image search results for careers – stereotype exaggeration and differences in representation – we next turn our attention to whether these differences affect people’s appraisals of the quality of search results and, in a hypothetical task, what image they choose to represent an occupation. This is not a purely abstract problem: a textbook publisher recently recalled a math textbook after discovering they had selected an image from a pornographic film for the cover [19].</p>
<p>We generated synthetic sets of image search results for each occupation, in which the gender balance was manipulated by re-ranking images from the original search results. Each synthetic result had a different gender distribution, with 8 images in each result. For each search term we generated up to 7 synthetic results: all men, all women, equal proportions, proportions from Google search, proportions from the BLS, the reverse of the proportions from Google search, and the reverse of the proportions in the BLS.</p>
<p>To ensure that the proportion of women in the BLS for a given search term does not influence the proportion of images in the synthetic results for that search term, synthetic subsets (other than equal) were only included if their corresponding reversed subset could also be included (for example, if we had enough women to make a synthetic search result with 6/8 images of women, but not enough men to make a synthetic search result with 6/8 images of men, neither synthetic result was included). This ensures that if gender has no effect on the probability of an image being selected, the baseline probability of two images of different gender being selected for any occupation will be the same: ⅛ (regardless of the gender ratio in that occupation).</p>
<p>To generate a subset with <em>k</em> women, we selected the top <em>k</em> female images from our labelled dataset (in the order they appeared in the original Google image search results) and the top 8-<em>k</em> male images. The images were displayed to participants in the order they appeared in the original search results. Participants could view one result set per occupation. This was to prevent participants from realizing that we manipulated the gender proportions of the search results, as they might if they saw multiple synthetic results for the same occupation with very different gender distributions.</p>
<p>On viewing a result set, we asked participants to select one image to illustrate the occupation for a hypothetical business presentation. We then asked them to describe how well the image results matched the search term (the occupation), in a drop down from 1 (very poor) to 5 (very good), and to describe why they rated as they did.</p>
<h3 id="image-selection-results">Image Selection Results</h3>
<p>We used logistic regression to model the probability that a given image is selected as the best result by a participant. Our model included image gender, the image gender proportion in BLS (see explanation under Study 2), participant gender, and their interactions. We also included all of the image adjective ratings to control for differences in qualitative representation.</p>
<pre class="sourceCode r"><code class="sourceCode r">selected_images =<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;data/public/selected_images.csv&quot;</span>)
selected_images =<span class="st"> </span><span class="kw">join</span>(selected_images, rated_images)

m.selected_image =<span class="st"> </span><span class="kw">glm</span>(image_selected ~<span class="st"> </span>bls_p_image_gender *<span class="st"> </span>image_gender *<span class="st"> </span>participant_gender +
<span class="st">    </span>professional +<span class="st"> </span>attractive +<span class="st"> </span>inappropriate +<span class="st"> </span>provocative +<span class="st"> </span>sexy +<span class="st"> </span>competent +<span class="st"> </span>trustworthy +<span class="st"> </span>weird, 
    <span class="dt">data=</span>selected_images, <span class="dt">family=</span>binomial)

<span class="kw">summary</span>(m.selected_image)</code></pre>
<table>
<caption>Fixed effects</caption>
<thead>
<tr class="header">
<th align="center"> </th>
<th align="center">Estimate</th>
<th align="center">Std. Error</th>
<th align="center">z value</th>
<th align="center">p</th>
<th align="center"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">(Intercept)</td>
<td align="center">-2.67</td>
<td align="center">0.2744</td>
<td align="center">-9.731</td>
<td align="center">2.23e-22</td>
<td align="center">***</td>
</tr>
<tr class="even">
<td align="center">bls_p_image_gender</td>
<td align="center">0.9387</td>
<td align="center">0.4152</td>
<td align="center">2.261</td>
<td align="center">0.02376</td>
<td align="center">*</td>
</tr>
<tr class="odd">
<td align="center">image_genderwoman</td>
<td align="center">0.2249</td>
<td align="center">0.3608</td>
<td align="center">0.6233</td>
<td align="center">0.5331</td>
<td align="center"></td>
</tr>
<tr class="even">
<td align="center">participant_gendermale</td>
<td align="center">0.04391</td>
<td align="center">0.3939</td>
<td align="center">0.1115</td>
<td align="center">0.9112</td>
<td align="center"></td>
</tr>
<tr class="odd">
<td align="center">professional</td>
<td align="center">-0.08313</td>
<td align="center">0.08171</td>
<td align="center">-1.017</td>
<td align="center">0.309</td>
<td align="center"></td>
</tr>
<tr class="even">
<td align="center">attractive</td>
<td align="center">-0.01925</td>
<td align="center">0.07924</td>
<td align="center">-0.2429</td>
<td align="center">0.8081</td>
<td align="center"></td>
</tr>
<tr class="odd">
<td align="center">inappropriate</td>
<td align="center">-0.03018</td>
<td align="center">0.1087</td>
<td align="center">-0.2776</td>
<td align="center">0.7813</td>
<td align="center"></td>
</tr>
<tr class="even">
<td align="center">provocative</td>
<td align="center">-0.3159</td>
<td align="center">0.1655</td>
<td align="center">-1.909</td>
<td align="center">0.05628</td>
<td align="center">.</td>
</tr>
<tr class="odd">
<td align="center">sexy</td>
<td align="center">-0.02669</td>
<td align="center">0.0872</td>
<td align="center">-0.3061</td>
<td align="center">0.7596</td>
<td align="center"></td>
</tr>
<tr class="even">
<td align="center">competent</td>
<td align="center">0.4691</td>
<td align="center">0.103</td>
<td align="center">4.553</td>
<td align="center">5.282e-06</td>
<td align="center">***</td>
</tr>
<tr class="odd">
<td align="center">trustworthy</td>
<td align="center">-0.1117</td>
<td align="center">0.08269</td>
<td align="center">-1.351</td>
<td align="center">0.1766</td>
<td align="center"></td>
</tr>
<tr class="even">
<td align="center">weird</td>
<td align="center">-0.4916</td>
<td align="center">0.1113</td>
<td align="center">-4.416</td>
<td align="center">1.006e-05</td>
<td align="center">***</td>
</tr>
<tr class="odd">
<td align="center">bls_p_image_gender:image_genderwoman</td>
<td align="center">-0.1885</td>
<td align="center">0.5857</td>
<td align="center">-0.3219</td>
<td align="center">0.7476</td>
<td align="center"></td>
</tr>
<tr class="even">
<td align="center">bls_p_image_gender:participant_gendermale</td>
<td align="center">-0.006446</td>
<td align="center">0.5957</td>
<td align="center">-0.01082</td>
<td align="center">0.9914</td>
<td align="center"></td>
</tr>
<tr class="odd">
<td align="center">image_genderwoman:participant_gendermale</td>
<td align="center">0.01022</td>
<td align="center">0.513</td>
<td align="center">0.01993</td>
<td align="center">0.9841</td>
<td align="center"></td>
</tr>
<tr class="even">
<td align="center">bls_p_image_gender:image_genderwoman:participant_gendermale</td>
<td align="center">-0.1601</td>
<td align="center">0.8342</td>
<td align="center">-0.1919</td>
<td align="center">0.8478</td>
<td align="center"></td>
</tr>
</tbody>
</table>
<p><em><strong>Table 1</strong>. Factors affecting image selection in Study 3. Coefficients are on a logit scale. Note the stereotype effect: greater % image gender in BLS is associated with higher probability that an image is selected.</em></p>
<h4 id="over-under--representation-and-participant-effects">Over-/under- representation and participant effects</h4>
<p>We found no evidence of systematic over-/under- representation of either gender (there were no significant effects of image gender). Neither were there significant effects of participant gender (suggesting men and women generally judge the best search result in the same way), nor any significant interactions with either of these factors.</p>
<h4 id="stereotype-exaggeration">Stereotype exaggeration</h4>
<p>As with the gender distributions in the search results themselves, we found evidence of stereotyping when people choose image results: image gender proportion in BLS had a significant effect on the probability of an image being selected; i.e., an image matching the majority gender proportion of its occupation was more likely to be selected. We believe this is consequence of stereotype matching: an image matching a person’s stereotype for that gender is more likely to be selected as an exemplar result.</p>
<p>We can see this effect by looking at the predicted probability that an image is selected given the proportion of people in that occupation having the gender of that image:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">visreg</span>(m.selected_image, <span class="st">&quot;bls_p_image_gender&quot;</span>, <span class="st">&quot;image_gender&quot;</span>, <span class="dt">scale=</span><span class="st">&quot;response&quot;</span>, <span class="dt">rug=</span><span class="ot">FALSE</span>)</code></pre>
<div class="figure">
<img src="figure/image_selected_by_bls_p_image_gender_visreg-1.png" alt="plot of chunk image_selected_by_bls_p_image_gender_visreg" /><p class="caption">plot of chunk image_selected_by_bls_p_image_gender_visreg</p>
</div>
<p>Or in the original data: (N.B. this is messy due to not accounting for qualitative differences, but still instructive in visualizing the effect in the raw data)</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(selected_images, <span class="kw">aes</span>(<span class="dt">x=</span>bls_p_image_gender, <span class="dt">fill=</span><span class="kw">factor</span>(image_selected, <span class="dt">levels=</span><span class="kw">c</span>(<span class="ot">TRUE</span>, <span class="ot">FALSE</span>)))) +<span class="st"> </span>
<span class="st">    </span><span class="kw">geom_bar</span>(<span class="dt">position=</span><span class="st">&quot;fill&quot;</span>, <span class="dt">binwidth=</span>.<span class="dv">1</span>) +<span class="st"> </span>
<span class="st">    </span><span class="kw">guides</span>(<span class="dt">fill=</span><span class="kw">guide_legend</span>(<span class="dt">title=</span><span class="st">&quot;image selected&quot;</span>)) +<span class="st"> </span>
<span class="st">    </span><span class="kw">ylim</span>(<span class="dv">0</span>, .<span class="dv">4</span>) +
<span class="st">    </span><span class="kw">geom_hline</span>(<span class="dt">yintercept=</span><span class="dv">1</span>/<span class="dv">8</span>, <span class="dt">lty=</span><span class="st">&quot;dashed&quot;</span>)        <span class="co"># reference line for &quot;chance&quot;</span></code></pre>
<div class="figure">
<img src="figure/image_selected_by_bls_p_image_gender_plot-1.png" alt="plot of chunk image_selected_by_bls_p_image_gender_plot" /><p class="caption">plot of chunk image_selected_by_bls_p_image_gender_plot</p>
</div>
<h3 id="search-result-quality-rating-results">Search Result Quality Rating Results</h3>
<p>We saw very similar effects influencing quality rating. We ran a mixed effects ordinal logistic regression to model quality rating based on proportion of women in BLS, proportion of women in the synthetic search result, participant gender, and their interactions. We included the adjective rating of the selected image (as possibly the most salient in judging search quality) in the synthetic search result to control for differences in qualita-tive representation. We also included participant and search term (occupation) as random effects. Results are in Table 2.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co">#build table of synthetic search result quality ratings with mean adjective ratings</span>
synthetic_searches =<span class="st"> </span><span class="kw">ddply</span>(selected_images, ~<span class="st"> </span>participant +<span class="st"> </span>participant_gender +<span class="st"> </span>search_term +
<span class="st">    </span>bls_p_women +<span class="st"> </span>search_p_women +<span class="st"> </span>synthetic_p_women +<span class="st"> </span>quality_rating, function(df) {
        selected.adj =<span class="st"> </span>df[df$image_selected,adjectives][<span class="dv">1</span>,]
        selected.adj
    })

<span class="co">#make quality ratings ordinal </span>
synthetic_searches$quality_rating =<span class="st"> </span><span class="kw">ordered</span>(synthetic_searches$quality_rating,
    <span class="dt">levels=</span><span class="kw">c</span>(<span class="st">&quot;very poor&quot;</span>, <span class="st">&quot;poor&quot;</span>, <span class="st">&quot;fair&quot;</span>, <span class="st">&quot;good&quot;</span>, <span class="st">&quot;very good&quot;</span>))

m.quality_rating =<span class="st"> </span><span class="kw">clmm</span>(quality_rating ~<span class="st"> </span>synthetic_p_women *<span class="st"> </span>bls_p_women *<span class="st"> </span>participant_gender +
<span class="st">    </span>professional +<span class="st"> </span>attractive +<span class="st"> </span>inappropriate +<span class="st"> </span>provocative +<span class="st"> </span>sexy +<span class="st"> </span>competent +<span class="st"> </span>trustworthy +<span class="st"> </span>weird +<span class="st"> </span>
<span class="st">    </span>(<span class="dv">1</span>|participant) +<span class="st"> </span>(<span class="dv">1</span>|search_term), <span class="dt">data=</span>synthetic_searches)

<span class="kw">summary</span>(m.quality_rating)</code></pre>
<table>
<caption>Random effects</caption>
<thead>
<tr class="header">
<th align="center">Groups</th>
<th align="center">Name</th>
<th align="center">Variance</th>
<th align="center">Std.Dev.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">participant</td>
<td align="center">(Intercept)</td>
<td align="center">1.6499</td>
<td align="center">1.2845</td>
</tr>
<tr class="even">
<td align="center">search_term</td>
<td align="center">(Intercept)</td>
<td align="center">2.2646</td>
<td align="center">1.5049</td>
</tr>
</tbody>
</table>
<table>
<caption>Fixed effects</caption>
<thead>
<tr class="header">
<th align="center"> </th>
<th align="center">Estimate</th>
<th align="center">Std. Error</th>
<th align="center">z value</th>
<th align="center">p</th>
<th align="center"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">synthetic_p_women</td>
<td align="center">-2.16</td>
<td align="center">0.8965</td>
<td align="center">-2.409</td>
<td align="center">0.016</td>
<td align="center">*</td>
</tr>
<tr class="even">
<td align="center">bls_p_women</td>
<td align="center">-3.113</td>
<td align="center">1.344</td>
<td align="center">-2.316</td>
<td align="center">0.02058</td>
<td align="center">*</td>
</tr>
<tr class="odd">
<td align="center">participant_gendermale</td>
<td align="center">0.219</td>
<td align="center">0.8672</td>
<td align="center">0.2525</td>
<td align="center">0.8007</td>
<td align="center"></td>
</tr>
<tr class="even">
<td align="center">professional</td>
<td align="center">-0.1323</td>
<td align="center">0.1864</td>
<td align="center">-0.7099</td>
<td align="center">0.4778</td>
<td align="center"></td>
</tr>
<tr class="odd">
<td align="center">attractive</td>
<td align="center">0.08522</td>
<td align="center">0.1776</td>
<td align="center">0.4797</td>
<td align="center">0.6314</td>
<td align="center"></td>
</tr>
<tr class="even">
<td align="center">inappropriate</td>
<td align="center">0.3792</td>
<td align="center">0.2463</td>
<td align="center">1.539</td>
<td align="center">0.1237</td>
<td align="center"></td>
</tr>
<tr class="odd">
<td align="center">provocative</td>
<td align="center">-0.417</td>
<td align="center">0.3288</td>
<td align="center">-1.268</td>
<td align="center">0.2046</td>
<td align="center"></td>
</tr>
<tr class="even">
<td align="center">sexy</td>
<td align="center">-0.01793</td>
<td align="center">0.2083</td>
<td align="center">-0.08609</td>
<td align="center">0.9314</td>
<td align="center"></td>
</tr>
<tr class="odd">
<td align="center">competent</td>
<td align="center">0.4569</td>
<td align="center">0.2241</td>
<td align="center">2.039</td>
<td align="center">0.0415</td>
<td align="center">*</td>
</tr>
<tr class="even">
<td align="center">trustworthy</td>
<td align="center">-0.1625</td>
<td align="center">0.209</td>
<td align="center">-0.7773</td>
<td align="center">0.437</td>
<td align="center"></td>
</tr>
<tr class="odd">
<td align="center">weird</td>
<td align="center">-0.4745</td>
<td align="center">0.2182</td>
<td align="center">-2.174</td>
<td align="center">0.02968</td>
<td align="center">*</td>
</tr>
<tr class="even">
<td align="center">synthetic_p_women:bls_p_women</td>
<td align="center">5.304</td>
<td align="center">1.704</td>
<td align="center">3.112</td>
<td align="center">0.001857</td>
<td align="center">**</td>
</tr>
<tr class="odd">
<td align="center">synthetic_p_women:participant_gendermale</td>
<td align="center">-0.6912</td>
<td align="center">1.225</td>
<td align="center">-0.5642</td>
<td align="center">0.5726</td>
<td align="center"></td>
</tr>
<tr class="even">
<td align="center">bls_p_women:participant_gendermale</td>
<td align="center">-0.4531</td>
<td align="center">1.358</td>
<td align="center">-0.3338</td>
<td align="center">0.7385</td>
<td align="center"></td>
</tr>
<tr class="odd">
<td align="center">synthetic_p_women:bls_p_women:participant_gendermale</td>
<td align="center">1.869</td>
<td align="center">2.323</td>
<td align="center">0.8045</td>
<td align="center">0.4211</td>
<td align="center"></td>
</tr>
</tbody>
</table>
<table>
<caption>Threshold coefficients</caption>
<thead>
<tr class="header">
<th align="center"> </th>
<th align="center">Estimate</th>
<th align="center">Std. Error</th>
<th align="center">z value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">very poor</td>
<td align="center">poor</td>
<td align="center">-5.131</td>
<td align="center">0.847</td>
</tr>
<tr class="even">
<td align="center">poor</td>
<td align="center">fair</td>
<td align="center">-3.539</td>
<td align="center">0.8133</td>
</tr>
<tr class="odd">
<td align="center">fair</td>
<td align="center">good</td>
<td align="center">-1.511</td>
<td align="center">0.7904</td>
</tr>
<tr class="even">
<td align="center">good</td>
<td align="center">very good</td>
<td align="center">0.866</td>
<td align="center">0.7852</td>
</tr>
</tbody>
</table>
<p><em><strong>Table 2</strong>. Factors affecting search result quality ratings in Study 3. Coefficients are on a logit scale.</em></p>
<h4 id="over-under--representation-and-participant-effects-1">Over-/under- representation and participant effects</h4>
<p>As above, we found no significant over-/under-representation effect: in an occupation with 50% women, we would not expect an all-male search result to be rated differently from an all-female search result (estimated difference = −0.41, SE = 0.47, z = −0.87, p = 0.38). As above, there were no significant effects of participant gender.</p>
<h4 id="stereotype-exaggeration-1">Stereotype exaggeration</h4>
<p>We again saw a stereotype exaggeration effect, manifested here as a significant interaction between proportion of women in BLS and proportion of women in the search result: in male-dominated occupations, search results with more males are preferred; in female-dominated occupations, search results with more females are preferred.</p>
<p>We can roughly see this effect in the data:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co">#plotting ordinal data against multiple dimensions is something of a pain.</span>
<span class="co">#Rather than resorting to treating it as continuous data, we&#39;ll group </span>
<span class="co">#BLS % women and % women in synthetic results into thirds in order to show </span>
<span class="co">#the effect of the interaction of both</span>
synthetic_searches$bls_p_women_thirds =<span class="st"> </span><span class="kw">ordered</span>(<span class="kw">symnum</span>(synthetic_searches$bls_p_women, 
    <span class="dt">cutpoints=</span><span class="dv">0</span>:<span class="dv">3</span>/<span class="dv">3</span>, <span class="dt">symbols=</span><span class="dv">1</span>:<span class="dv">3</span>), 
    <span class="dt">labels=</span><span class="kw">c</span>(<span class="st">&quot;&lt; 1/3 women in BLS&quot;</span>,<span class="st">&quot;1/3 - 2/3 women in BLS&quot;</span>,<span class="st">&quot;&gt; 2/3 women in BLS&quot;</span>))
   
<span class="kw">ggplot</span>(synthetic_searches, <span class="kw">aes</span>(<span class="dt">x=</span>synthetic_p_women, <span class="dt">fill=</span>quality_rating, <span class="dt">order=</span>-<span class="kw">as.numeric</span>(quality_rating))) +<span class="st"> </span>
<span class="st">    </span><span class="kw">geom_bar</span>(<span class="dt">position=</span><span class="st">&quot;fill&quot;</span>, <span class="dt">breaks=</span><span class="dv">0</span>:<span class="dv">3</span>/<span class="dv">3</span>) +<span class="st"> </span>
<span class="st">    </span><span class="kw">scale_fill_brewer</span>(<span class="dt">type=</span><span class="st">&quot;seq&quot;</span>) +<span class="st"> </span>
<span class="st">    </span><span class="kw">facet_wrap</span>(~bls_p_women_thirds)</code></pre>
<div class="figure">
<img src="figure/quality_rating_stereotype_plot-1.png" alt="plot of chunk quality_rating_stereotype_plot" /><p class="caption">plot of chunk quality_rating_stereotype_plot</p>
</div>
<p>Viewed from the perspective of this task, these results make sense: we asked people to select the best search result (or to rate the quality of all results), and they tended to prefer images matching their mental image of each profession, both in qualitative characteristics and in expected gender. This reflects the strong sense that people have of expected gender proportions in a broad spectrum of occupations, which we explore in more detail next. This also emphasizes an important tension between possible broader societal goals in manipulating gender as a design dimension in search results versus end-users’ quality expectations, an issue we discuss in detail at the end of this paper.</p>
<h2 id="study-4-perceptions-of-gender-proportions-in-occupations">Study 4: Perceptions of gender proportions in occupations</h2>
<p>Finally, we sought to understand whether and how gender proportions in image search results can affect people’s perceptions of the actual prevalence of men and women in different occupations, both to understand how existing (stereotype-exaggerating, misrepresented) results might be affecting people’s perceptions of gender proportions and how feasible manipulating gender distributions in image search might be as a method for affecting those perceptions. This gets at a primary motivation of our paper: opening up gender proportions as a design dimension in image search.</p>
<p>Given the many possible day-to-day influences on perceptions of the prevalence of genders in different fields, we chose to collect people’s baseline perceptions, wait two weeks, show them a synthetic image search result set for the same career, and then immediately ask them their perceptions of prevalence.</p>
<p>We asked each participant the demographics information we used in studies 2 and 3. Then for each career we asked what percent of people working in that career in the US are women, alongside three distraction questions: what education they believe is typical for someone in that career, whether they believe the career was growing, and how prestigious they think it is. Participants could answer for as many careers as they wished.</p>
<p>After two weeks, each participant received an email thanking them for their prior participation and inviting them to participate in a new round of tasks; we limited access both in the script that managed our tasks and using an assigned qualification on Mechanical Turk. For each profession to which they had previously responded, we returning participants to view a synthetic search result and complete the image search task from study 3; on the next page we re-asked the four questions from the first page: typical education for the career, percent women, whether the career was growing, and its prestige.</p>
<h3 id="results-2">Results</h3>
<h4 id="perceptions-absent-influence">Perceptions absent influence</h4>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co">#This is the full set of people who did the first part of the task (stating their</span>
<span class="co">#perceived gender proportions of occupations). Not all of these participants</span>
<span class="co">#returned to fill out part 2 (the post-manipulation) </span>
manipulated_perceptions_pre =<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;data/public/manipulated_perceptions_pre.csv&quot;</span>)

m.pre_manipulation =<span class="st"> </span><span class="kw">lmer</span>(perceived_p_women_1 ~<span class="st"> </span>bls_p_women +<span class="st"> </span>
<span class="st">    </span>(<span class="dv">1</span>|participant), 
    <span class="dt">data=</span>manipulated_perceptions_pre)

<span class="kw">summary</span>(m.pre_manipulation)</code></pre>
<pre><code>Random effects:
 Groups      Name        Std.Dev.
 participant (Intercept) 0.049814
 Residual                0.134069</code></pre>
<table>
<caption>Fixed effects. Linear mixed model fit by REML t-tests use Satterthwaite approximations to degrees of freedom</caption>
<thead>
<tr class="header">
<th align="center"> </th>
<th align="center">Estimate</th>
<th align="center">Std. Error</th>
<th align="center">df</th>
<th align="center">t value</th>
<th align="center">p</th>
<th align="center"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">(Intercept)</td>
<td align="center">0.08139</td>
<td align="center">0.01807</td>
<td align="center">34.47</td>
<td align="center">4.505</td>
<td align="center">7.273e-05</td>
<td align="center">***</td>
</tr>
<tr class="even">
<td align="center">bls_p_women</td>
<td align="center">0.7312</td>
<td align="center">0.02479</td>
<td align="center">297.9</td>
<td align="center">29.5</td>
<td align="center">0</td>
<td align="center">***</td>
</tr>
</tbody>
</table>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">r.squaredGLMM</span>(m.pre_manipulation)</code></pre>
<pre><code>##       R2m       R2c 
## 0.7165295 0.7509160</code></pre>
<p>People’s initial perceptions of gender proportions in occupations are quite good. We assessed the correlation of their existing perceptions to real-world proportions using a mixed-effects linear regression with gender proportions in BLS as the fixed effect and participant as a random effect. The marginal pseudo-R<sup>2</sup> of this model was 0.717 (F1,297.71 = 870.21, p &lt; 0.0001). A plot of partial residuals shows the correspondence:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">visreg</span>(m.pre_manipulation, <span class="st">&quot;bls_p_women&quot;</span>)</code></pre>
<div class="figure">
<img src="figure/perceptions_before_manipulation_visreg-1.png" alt="plot of chunk perceptions_before_manipulation_visreg" /><p class="caption">plot of chunk perceptions_before_manipulation_visreg</p>
</div>
<h4 id="perceptions-after-influence">Perceptions after influence</h4>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co">#Not all of the participants above returned to fill out part 2.</span>
<span class="co">#In this part we examine only those who returned. </span>
manipulated_perceptions_post =<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;data/public/manipulated_perceptions_post.csv&quot;</span>)
m.post_manipulation =<span class="st"> </span><span class="kw">lmer</span>(perceived_p_women_2 ~<span class="st"> </span>synthetic_p_women +<span class="st"> </span>perceived_p_women_1 +<span class="st"> </span>
<span class="st">    </span>(perceived_p_women_1|participant), 
    <span class="dt">data=</span>manipulated_perceptions_post)

<span class="kw">summary</span>(m.post_manipulation)</code></pre>
<pre><code>Random effects:
 Groups      Name                Std.Dev. Corr  
 participant (Intercept)         0.10568        
             perceived_p_women_1 0.19221  -1.000
 Residual                        0.10140        </code></pre>
<table>
<caption>Fixed effects. Linear mixed model fit by REML t-tests use Satterthwaite approximations to degrees of freedom</caption>
<thead>
<tr class="header">
<th align="center"> </th>
<th align="center">Estimate</th>
<th align="center">Std. Error</th>
<th align="center">df</th>
<th align="center">t value</th>
<th align="center">p</th>
<th align="center"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">(Intercept)</td>
<td align="center">0.09859</td>
<td align="center">0.03442</td>
<td align="center">15.71</td>
<td align="center">2.864</td>
<td align="center">0.0114</td>
<td align="center">*</td>
</tr>
<tr class="even">
<td align="center">synthetic_p_women</td>
<td align="center">0.06727</td>
<td align="center">0.02316</td>
<td align="center">202.2</td>
<td align="center">2.905</td>
<td align="center">0.004087</td>
<td align="center">**</td>
</tr>
<tr class="odd">
<td align="center">perceived_p_women_1</td>
<td align="center">0.7488</td>
<td align="center">0.06034</td>
<td align="center">10.35</td>
<td align="center">12.41</td>
<td align="center">1.513e-07</td>
<td align="center">***</td>
</tr>
</tbody>
</table>
<p><em><strong>Table 3</strong>. Effects of the manipulated search result and a person’s pre-existing opinion of % women in an occupation on their opinion after seeing the manipulated result (Study 4).</em></p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">r.squaredGLMM</span>(m.post_manipulation)</code></pre>
<pre><code>##       R2m       R2c 
## 0.6986316 0.7624350</code></pre>
<p>After exposure to search results with manipulated gender proportions, estimates shifted slightly in the direction of the manipulated proportions. We ran a linear mixed-effects regression to predict perceived gender proportions, with initial perceived gender proportion and manipulated search gender proportion as fixed effects and participant as a random effect. Both fixed effects were significant: while a person’s original perceptions of an occupation dominated their opinion two weeks later; approximately 7% of a person’s subsequent opinion on average was determined by the result set they were exposed to (p &lt; 0.01, see Table 3).</p>
<p>We can see the strong association with their pre-existing opinion:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">visreg</span>(m.post_manipulation, <span class="st">&quot;perceived_p_women_1&quot;</span>)</code></pre>
<div class="figure">
<img src="figure/perceptions_after_manipulation_vs_before_visreg-1.png" alt="plot of chunk perceptions_after_manipulation_vs_before_visreg" /><p class="caption">plot of chunk perceptions_after_manipulation_vs_before_visreg</p>
</div>
<p>And the much weaker (but present) effect of the manipulated search results:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">visreg</span>(m.post_manipulation, <span class="st">&quot;synthetic_p_women&quot;</span>)</code></pre>
<div class="figure">
<img src="figure/perceptions_after_manipulation_vs_search_visreg-1.png" alt="plot of chunk perceptions_after_manipulation_vs_search_visreg" /><p class="caption">plot of chunk perceptions_after_manipulation_vs_search_visreg</p>
</div>
<p>While this only shows short-term movement due to manipulated search results, cultivation theory suggests that long-term, ongoing exposure to such results might shift perceptions over time. This suggests that there may be value in considering gender distribution as a more deliberate design dimension in image search results, as we discuss next.</p>
<h2 id="discussion">Discussion</h2>
<p>Our results provide guidance on the short-term effects of possible changes to search engine algorithms and highlight tensions in possible designs of search algorithms.</p>
<h3 id="as-a-design-space-what-other-kinds-of-search-results-could-we-design-and-what-might-be-the-consequences">As a design space, what other kinds of search results could we design and what might be the consequences?</h3>
<p>There are two sets of adjustments that can be made: adjusting the gender distribution, and adjusting the distribution of qualitative image characteristics within genders (e.g. increasing the proportion of female construction worker results that are rated as professional or competent to correct for the sexy construction worker problem). Taking the former as a starting point, we outline three possible (amongst many) ways of adjusting search results: 1) exaggerating, or continuing to accept, exaggerated gender stereotypes; 2) aligning the gender balance of results to match reality; or 3) balancing the genders represented in results.</p>
<p>These models also surface several design tensions in this space. In particular, we might ask if our goal is to improve perceptions of search result quality, or to advance a broader social agenda to shift perceptions of gender equality in various professions. While potentially at odds in the short term (e.g., highly stereotyped results might be highly rated but not have desirable societal effects), cultivation theory also suggests these goals may not be as contrary over the long term if perceptions can be shifted to match a broader goal of equal representation (as, at least in the short term, Study 4 suggests is possible). We discuss how these motivations interact in more detail for each proposed model. We do not wish to come down on any side of these issues, but wish to advance an understanding of how the choices people make in designing algorithms can (and already do) define a design space that explicitly or implicitly affects these issues.</p>
<ol style="list-style-type: decimal">
<li><p><strong>Stereotype model</strong>. Exaggerate gender stereotypes. This might improve subjective assessment of quality over baseline results if the dominant gender is already represented as professional and appropriate, so would likely not require correcting for qualitative differences (simplifying the technical problem). This would also give more exemplars for the selection task. At the same time, continuing to portray careers as more gender segregated than they are, or even further exaggerating gender imbalances, has the disadvantage of potentially influencing people’s perceptions of occupation gender distributions over time to be less accurate and reinforcing stereotypes that can shape and limit career aspirations and treatment.</p></li>
<li><p><strong>Reality model</strong>. Correct the slight stereotype exaggeration and underrepresentation of women seen in the data so that gender distributions better resemble the BLS. So long as we can select images of the non-dominant gender that have high professionalism and low inappropriateness, this would at least better represent the reality of the profession while having little effect on the perceived search result quality or the selection task. Over the long term, exposure to such results might improve people’s estimations of real-world gender proportions in occupations. This also represents only a small perturbation to existing results, and may not even require adjustments to distributions to account for qualitative differences in representation due to how close the existing search proportions are to actual BLS proportions.</p></li>
<li><p><strong>Balanced model</strong>. Adjust the gender proportions in occupations to be equal or closer to equal. This may impair the selection task by giving fewer gender exemplars. However, if this is paired with corrections for qualitative differences in representation so that portrayals of the non-dominant gender are similar to the dominant one (particularly for professionalism), we do not believe it would significantly degrade people’s overall perceptions of the quality of the results. This model exposes a tension between a desire for results perceived as high-quality and possible societal goals for advancing equal representation. While the short-term effects on perceived search result quality would likely be negative, both cultivation theory [32] and the results of study 4 predict that this could, in the long term, shift people’s perceptions towards a less gender-stereotyped view of these professions. Along with that long-term shift, a possible result may be that perceptions of quality shift back as people begin to perceive gender proportions as more equal.</p></li>
</ol>
<h3 id="feasibility-of-manipulating-representation">Feasibility of Manipulating Representation</h3>
<p>Automatic gender classification of images of people is an outstanding problem. While state-of-the art classifiers perform well under certain circumstances, they have historically focused on straight-on images of a single face, typically without visual occlusions, uneven lighting, or complicated backgrounds [26]. However, recent studies on gender classification on images collected in the wild [1,31] or of only partial features [24] strongly suggest that automated solutions will soon reach or surpass the accuracy of human annotators. Meanwhile, automated human labelling of these images would not be much more costly than the data collection processes used in this paper, and would provide ground truth data for future automated approaches.</p>
<h3 id="limitations-and-future-work">Limitations and Future Work</h3>
<p>We have focused here on search results absent personalization or other additional context (such as time of year or location) that may affect results shown to users in real-world tasks. While the businessperson making a slide presentation might be seeking an accurate depiction of a given profession, other users with different goals might prefer caricatured or inaccurate portrayals, such as the sexy construction worker. We also do not address the cause of the biases and misrepresentation found (e.g., are these due to actual prevalence in webpages, or due to the ranking algorithms used by Google?). Future work might try to tease these effects apart, and to investigate these phenomena in other types of image search, such as on photo sharing sites and in social media. To aid in replication, our data and code are available online <a href="https://github.com/mjskay/gender-in-image-search">here</a>.</p>
<h2 id="conclusion">Conclusion</h2>
<p>Academics and the technology community have raised concerns about potential biases in search engines and in stock photos. We contribute an assessment of gender representation in image search results and its effects on perceived search result quality, images selected, and perceptions about reality. We find that image search results for occupations slightly exaggerate gender stereotypes and portray the minority gender for an occupational less professionally. There is also a slight underrepresentation of women. This stereotype exaggeration is consistent with perceptions of result quality – people believe results are better when they agree with the stereotype – but risks reinforcing or even increasing perceptions of actual gender segregation in careers.</p>
<p>Addressing concerns such as these in search engines and other information sources, however, requires balancing design tensions. For example, maintaining perceived search quality and accurately representing available materials may be at odds with supporting socially desirable outcomes and representing either real-world distributions of careers or idealized distributions of careers. We hope to advance a constructive discussion on gender representation as a design dimension (explicit and implicit) in information systems.</p>
<h2 id="acknowledgements">Acknowledgements</h2>
<p>We thank Gilbert Bernstein and Benjamin Mako Hill for their valuable feedback on this work.</p>
<h2 id="footnotes">Footnotes</h2>
<ol style="list-style-type: decimal">
<li><p><a name="footnote1" href="#footnote1_source">^</a> We use “turkers” for studies 1 and 2, where they were asked only to label data, and “participants” for studies 3 and 4, where their opinions and perceptions were solicited.</span></p></li>
<li><p><a name="footnote2" href="#footnote2_source">^</a> As the BLS uses only binary gender classifications, we also restricted labels to binary gender classification here.</p></li>
<li><p><a name="footnote3" href="#footnote3_source">^</a> This test was carried out using the stereotyped model, but we note that a similar test carried out on the non-stereotyped model yielded similar results and confidence intervals.</p></li>
<li><p><a name="footnote4" href="#footnote4_source">^</a> While we have used worker and image as random effects here and elsewhere in the paper, where estimable we have also compared results with fixed effects models and found similar effects. We believe random effects to be more appropriate here as some workers have completed only a small number of tasks.</p></li>
</ol>
<h2 id="references">References</h2>
<ol style="list-style-type: decimal">
<li><p>Arigbabu OA; Ahmad SMS, Adnan WAN, Yussof S, Iranmanesh V, Malallah, FL, Gender recognition on real world faces based on shape representation and neural network. ICCOINS 2014.</p></li>
<li><p>Baker P, Potts A. “Why do white people have thin lips?” Google and the perpetuation of stereotypes via auto-complete search forms. Crit Disc St 10(2): 187-204.</p></li>
<li><p>Behm-Morawitz E, Mastro D. The Effects of the Sexualization of Female Video Game Characters on Gender Stereotyping and Female Self-Concept. Sex Roles 2009; 61(11-12): 808-823.</p></li>
<li><p>Bodenhausen GV, Wyer RS. Effects of stereotypes in decision making and information-processing strategies. J Pers Soc Psychol 1985; 48(2): 267.</p></li>
<li><p>Bureau of Labor Statistics. Labor Force Statistics from the Current Population Survey, Section 11. 5 February 2013. http://www.bls.gov/cps/aa2012/cpsaat11.htm.</p></li>
<li><p>Coltrane S, Adams M. Work–family imagery and gender stereotypes: Television and the reproduction of difference. J Vocat Behav 1997; 50(2): 323-347.</p></li>
<li><p>Correll SJ. Gender and the career choice process: The role of biased self-assessments. Am J Sociol 2001; 106(6): 1691–1730.</p></li>
<li><p>Correll SJ. Constraints into preferences: Gender, status, and emerging career aspirations. Am Sociol Rev 2004; 69(1): 93-113.</p></li>
<li><p>Executive Office of the President. Big Data: Seizing Opportunities, Preserving Values. May 2014.</p></li>
<li><p>Friedman B, Nissenbaum H. Bias in computer systems. ACM T Inform Syst 1996; 14(3): 330-347.</p></li>
<li><p>Gerbner G, Gross L, Morgan M, Signorielli N. Living with television: The dynamics of the cultivation process. Perspectives on media effects 1986: 17-40.</p></li>
<li><p>Graves SB. Television and Prejudice Reduction: When Does Television as a Vicarious Experience Make a Difference? J Soc Issues 1999; 55(4): 707-727.</p></li>
<li><p>Grossman P. New Partnership with LeanIn.org. InFocus by Getty Images. http://infocus.gettyimages.com/post/new-partnership-with-leaninorg.</p></li>
<li><p>Halpert JA, Wilson ML, Hickman JL. Pregnancy as a source of bias in performance appraisals. J Organ Behav 1993.</p></li>
<li><p>Haslam SA, Turner JC, Oakes PJ, Reynolds KJ, Doosje, B From personal pictures in the head to collective tools in the word: how shared stereotypes allow groups to represent and change social reality. In C McGarty, VY Yzerbyt, R Spears (eds.). Stereotypes as explanations: The formation of meaningful beliefs about social groups 2002. Cambridge University Press, 157-185.</p></li>
<li><p>Heilman ME. Description and prescription: How gender stereotypes prevent women's ascent up the organizational ladder. J Soc Issues 2001; 57(4): 657-674.</p></li>
<li><p>Heilman ME. Okimoto, TG. 2008. Motherhood: A potential source of bias in employment decisions. J Appl Psychol 2008; 93(1): 189-198.</p></li>
<li><p>Hilton JL, &amp; Von Hippel W. Stereotypes. Annu Rev Psychol 1996; 47(1): 237-271.</p></li>
<li><p>Hooper B. Porn star appears on cover of Thai math textbook. United Press International. http://upi.com/5031410787947</p></li>
<li><p>Introna L, Nissenbaum H. Defining the web: The politics of search engines. Computer 2000; 33(1): 54-62.</p></li>
<li>Jacobs J. Gender Inequality at Work. Thousand Oaks, CA: SAGE Publications,</li>
<li></li>
<li><p>Kammerer,Y, Gerjets P. How search engine users evaluate and select Web search results: The impact of the search engine interface on credibility assessments. Libr Inform Sci 2012; 4: 251–279.</p></li>
<li><p>Keane MT, O'Brien M, Smyth B. Are people biased in their use of search engines? Commun ACM 2008; 51(2): 49-52.</p></li>
<li><p>Khorsandi R, Abdel-Mottaleb M. Gender classification using 2-D ear images and sparse representation. 2013 IEEE Workshop on Applications of Computer Vision (WACV), 461-466.</p></li>
<li><p>Lean In Foundation. Getty Image Collection. http://leanin.org/getty.</p></li>
<li><p>Makinen E, Raisamo R. Evaluation of Gender Classification Methods with Automatically Detected and Aligned Faces, IEEE T Pattern Anal 2008; 30(3): 541-547.</p></li>
<li><p>Massey D. Categorically Unequal: The American Stratification System. NY: Russell Sage Foundation, 2007.</p></li>
<li><p>Miller CC. 10 February 2014. LeanIn.org and Getty Aim to Change Women’s Portrayal in Stock Photos. New York Times, B3. http://nyti.ms/1eLY7ij</p></li>
<li><p>Pariser E. The Filter Bubble: What the Internet Is Hiding from You. 2011. Penguin Press.</p></li>
<li><p>Potter WJ. Cultivation theory and research, Hum Commun Res 1993; 19(4): 564-601.</p></li>
<li><p>Shan C. Learning local binary patterns for gender classification on real-world face images, Pattern Recogn Lett 2012; 33(4), 431-437.</p></li>
<li><p>Shrum LJ. Assessing the Social Influence of Television A Social Cognition Perspective on Cultivation Effects. Commun Res 1995; 22(4): 402-429.</p></li>
<li><p>Spencer SJ, Steele CM, Quinn DM. Stereotype threat and women's math performance. J Exp Soc Psychol 1999; 35(1): 4-28.</p></li>
<li><p>Snyder M, Tanke ED, Berscheid E. Social perception and interpersonal behavior: On the self-fulfilling nature of social stereotypes. J Pers Soc Psychol 1977; 35(9): 656–666.</p></li>
<li><p>Sweeney L. Discrimination in online ad delivery. Commun ACM 2013; 56(5): 44-54.</p></li>
<li><p>Tajfel H. Social stereotypes and social groups. In Turner JC, Giles H. Intergroup Behaviour 1981. Oxford: Blackwell. 144–167.</p></li>
<li><p>Vaughan L, Thelwall M. Search engine coverage bias: evidence and possible causes. Inform Process Manag 2004; 40(4): 693-707.</p></li>
<li><p>Williams D. Virtual Cultivation: Online Worlds, Offline Perceptions. J Commun 1996; 56(1): 69–87.</p></li>
<li><p>Word CO, Zanna MP, Cooper J. The nonverbal mediation of self-fulfilling prophecies in interracial interaction. J Exp Soc Psychol 1974; 10(2): 109–120.</p></li>
<li><p>X Tang, K Liu, J Cui, F Wen, X Wang. IntentSearch: Capturing User Intention for One-Click Internet Image Search, IEEE T Pattern Anal 34(7): 1342-1353.</p></li>
<li><p>Zha ZJ, Yang L, Mei T, Wang M, Wang Z, Chua TS, Hua XS. 2010. Visual query suggestion: Towards capturing user intent in internet image search. ACM T Multim Comput 2010; 6(3): a13.</p></li>
</ol>
</body>
</html>
